number_of_columns:
  - columns_length: 12

columns:
  - case_id: object
  - case_status: object
  - continent: object
  - education_of_employee: object
  - full_time_position: object
  - has_job_experience: object
  - no_of_employees: int64
  - prevailing_wage: float64
  - region_of_employment: object
  - requires_job_training: object
  - unit_of_wage: object
  - yr_of_estab: int64

numerical_columns:
  - no_of_employees
  - prevailing_wage
  - yr_of_estab


categorical_columns:
  - case_id
  - continent
  - education_of_employee
  - has_job_experience
  - requires_job_training
  - region_of_employment
  - unit_of_wage
  - full_time_position
  - case_status

drop_columns:
  - case_id
  - yr_of_estab

  # for data transformation
num_features:
  - no_of_employees
  - prevailing_wage
  - company_age

or_columns:
  - has_job_experience
  - requires_job_training
  - full_time_position
  - education_of_employee

oh_columns:
  - continent
  - unit_of_wage
  - region_of_employment

transform_columns:
  - no_of_employees
  - company_age


